### ISSUE TITLE
[BUG] Unhandled throttling exception while creating slurm_nodes.conf

### ISSUE THREAD

**Issue by cartalla** [aws-samples/aws-eda-slurm-cluster#114]
**Describe the bug**
The slurm controller playbook failed with the following exception:

```
INFO:2023-03-16 16:01:49,358: Getting EC2 instance info for us-east-1 (US East (N. Virginia))
    ERROR:2023-03-16 16:02:17,587: Unhandled exception in SlurmPlugin.create_node_conf
    Traceback (most recent call last):
      File "/opt/slurm/slurmeda2/bin/SlurmPlugin.py", line 1628, in create_node_conf
        eC2InstanceTypeInfo = EC2InstanceTypeInfo(compute_regions, json_filename=self.args.instance_type_info_json, debug=self.args.debug > 1)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 81, in __init__
        self.get_instance_type_info(region)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 243, in get_instance_type_info
        StartTime = datetime.now()
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeSpotPriceHistory operation (reached max retries: 4): Request limit exceeded.
    ERROR:root:Unhandled exception in ./slurm_ec2_create_node_conf.py
    Traceback (most recent call last):
      File "./slurm_ec2_create_node_conf.py", line 33, in <module>
        plugin.create_node_conf()
      File "/opt/slurm/slurmeda2/bin/SlurmPlugin.py", line 1628, in create_node_conf
        eC2InstanceTypeInfo = EC2InstanceTypeInfo(compute_regions, json_filename=self.args.instance_type_info_json, debug=self.args.debug > 1)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 81, in __init__
        self.get_instance_type_info(region)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 243, in get_instance_type_info
        StartTime = datetime.now()
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeSpotPriceHistory operation (reached max retries: 4): Request limit exceeded.
    Traceback (most recent call last):
      File "./slurm_ec2_create_node_conf.py", line 33, in <module>
        plugin.create_node_conf()
      File "/opt/slurm/slurmeda2/bin/SlurmPlugin.py", line 1628, in create_node_conf
        eC2InstanceTypeInfo = EC2InstanceTypeInfo(compute_regions, json_filename=self.args.instance_type_info_json, debug=self.args.debug > 1)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 81, in __init__
        self.get_instance_type_info(region)
      File "/opt/slurm/slurmeda2/bin/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 243, in get_instance_type_info
        StartTime = datetime.now()
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeSpotPriceHistory operation (reached max retries: 4): Request limit exceeded.
```

**Additional context**

**Comment by cartalla** [comment]
The following boto3.client objects are created:
* ec2_client
  * describe_regions not decorated
* self.pricing_client
  * get_products already decorated
* self.ec2
  * describe_availability_zones not decorated
  * get_paginator not decorated
  * paginate not decorated
  * describe_spot_price_history not decorated
