### ISSUE TITLE
[BUG] HPC6a CPUOptions are not allowed when launching an instance

### ISSUE THREAD

**Issue by biroca** [aws-samples/aws-eda-slurm-cluster#122]
**Describe the bug**

```
ERROR:2023-05-04 14:56:11,660: Not retrying exception
Traceback (most recent call last):
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 117, in f_retry
    return f(*args, **kwargs)
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 179, in launch_instance
    self.result = self.plugin.ec2[self.region].run_instances(**self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnsupportedOperation) when calling the RunInstances operation: The hpc6a.48xlarge instance type does not support specifying CpuOptions.
ERROR:2023-05-04 14:56:11,661: Failed to create use2-az2-c7-x86-hpc6a-48xl-ondemand-0. Marking down with reason='UnsupportedOperation'.
Traceback (most recent call last):
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 157, in run
    self.launch_instance()
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 123, in f_retry
    raise e
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 117, in f_retry
    return f(*args, **kwargs)
  File "/opt/slurm/bcaslurmpoc/bin/SlurmPlugin.py", line 179, in launch_instance
    self.result = self.plugin.ec2[self.region].run_instances(**self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnsupportedOperation) when calling the RunInstances operation: The hpc6a.48xlarge instance type does not support specifying CpuOptions.

INFO:2023-05-04 14:56:11,668: Setting use2-az2-c7-x86-hpc6a-48xl-ondemand-0 to drain so new jobs do not run on it.
INFO:2023-05-04 14:56:11,681: use2-az2-c7-x86-hpc6a-48xl-ondemand-0 draining
INFO:2023-05-04 14:56:11,681: Requeuing jobs on use2-az2-c7-x86-hpc6a-48xl-ondemand-0 because UnsupportedOperation
INFO:2023-05-04 14:56:11,693: Jobs running on use2-az2-c7-x86-hpc6a-48xl-ondemand-0:
```

**Comment by cartalla** [comment]
Which AWS region are you running in, us-east-2?

**Comment by cartalla** [comment]
I haven't tested it with hpc6a yet, but I've pushed what I think will fix the problem if you want to try it on the following branch:

122-bug-hpc6a-cpuoptions-are-not-allowed-when-launching-an-instance

**Comment by cartalla** [comment]
Still working through some bugs. Will update when tested.

**Comment by cartalla** [comment]
Got it to try to launch an hpc6a.48xlarge and it failed because there is no capacity in us-east-2a. The capacity is all in us-east-2b.

I looked and didn't see anything in the instance type information that indicates this. It also doesn't seem to be in the pricing plans. So, I guess you just have to know? Not nice.
