### ISSUE TITLE
[DOCS] Baseline setup instructions from a clean AMI

### ISSUE THREAD

**Issue by kaisenl** [aws-samples/aws-eda-slurm-cluster#193]
**Is your feature request related to a problem? Please describe.**
I'm trying to run install.sh and it seems to make some assumptions about what OS I'm running, and what I have installed. It also seems to have a problem validating the default config. I'm guessing you have an existing workspace, which works for you.

**Describe the solution you'd like**
Some documentation or scripts that can get this working from a clean base AMI like ALinux2023. That way there's a good known version, and no version mismatches for tooling or libraries.

**Comment by cartalla** [comment]
Thanks for reporting the issue. I do most of my testing using Amazon Linux 2. I haven't tested with Amazon Linux 2023. I have done testing in the past with RHEL 8 and RHEL 9.

**Comment by kaisenl** [comment]
Let me know if I should open a separate issue for this, but I setup a clean ALinux2 instance, checked out the code, and ran `install.sh`, and it errored out with the following:

```
Working directory: /home/ec2-user/aws-eda-slurm-cluster/source
INFO:
====== Validating AWS environment ======

INFO: Using default config: /home/ec2-user/aws-eda-slurm-cluster/source/resources/config/default_config.yml
/home/ec2-user/aws-eda-slurm-cluster/source/.venv/lib64/python3.7/site-packages/boto3/compat.py:82: PythonDeprecationWarning: Boto3 will no longer support Python 3.7 starting December 13, 2023. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.8 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)
Traceback (most recent call last):
  File "source/installer.py", line 31, in <module>
    app.main()
  File "/home/ec2-user/aws-eda-slurm-cluster/source/slurm_installer/installer.py", line 114, in main
    self.config = self.get_config(args.config_file)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/slurm_installer/installer.py", line 453, in get_config
    validated_config = check_schema(config_parameters)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 548, in check_schema
    config_schema = get_config_schema(config_in)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 442, in get_config_schema
    Optional('SlurmRestApiVersion', default=get_slurm_rest_api_version(config)): str,
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 146, in get_slurm_rest_api_version
    slurm_version = get_PC_SLURM_VERSION(config)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 142, in get_PC_SLURM_VERSION
    parallel_cluster_version = get_parallel_cluster_version(config)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 127, in get_parallel_cluster_version
    return config['slurm']['ParallelClusterConfig']['Version']
KeyError: 'Version'
```

**Comment by cartalla** [comment]
You can try checking out the bug fix branch:

```
git fetch
git checkout 193-docs-baseline-setup-instructions-from-a-clean-ami
```

**Comment by kaisenl** [comment]
Thanks! This one got a little further. I went with `./installer.sh --prompt` to fill out the missing fields, but still ran into this issue.

```
INFO: ErrorSnsTopicArn     set from command line: None
INFO: slurm/SubmitterSecurityGroupIds in config file overridden on command line from {} to {'default hpc grid': 'sg-01f6a0a2b8dc0c8fc'}
INFO: slurm/ClusterName defaulted to slurmminimal
ERROR: Invalid config
Traceback (most recent call last):
  File "/home/ec2-user/aws-eda-slurm-cluster/source/.venv/lib64/python3.7/site-packages/schema.py", line 405, in validate
    nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value, **kwargs)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/.venv/lib64/python3.7/site-packages/schema.py", line 440, in validate
    raise SchemaUnexpectedTypeError(message, e.format(data) if e else None)
schema.SchemaUnexpectedTypeError: None should be instance of 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/cdk_slurm_stack.py", line 457, in check_config
    validated_config = check_schema(self.config)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/cdk/config_schema.py", line 551, in check_schema
    validated_config = config_schema.validate(config_in)
  File "/home/ec2-user/aws-eda-slurm-cluster/source/.venv/lib64/python3.7/site-packages/schema.py", line 409, in validate
    raise SchemaError([message] + x.autos, [e.format(data) if e else None] + x.errors)
schema.SchemaError: Key 'ErrorSnsTopicArn' error:
None should be instance of 'str'
```

**Comment by cartalla** [comment]
Try `git pull -r` and try again. This should be fixed if you don't have an SNS topic.
