### ISSUE TITLE
[BUG] Deployment fails if we do not set the MungeKeySsmParameter

### ISSUE THREAD

**Issue by deeppat** [aws-samples/aws-eda-slurm-cluster#21]
**Describe the bug**
If you try to deploy the eda slurm cluster with the default config file with the `MungeKeySsmParameter` commented out, cdk still tries to find it in your account and fails deployment when it doesn't find the key.

For eg. my config file has it commented:
```
  #MungeKeySsmParameter: "/slurm/munge_key"
```

**To Reproduce**
1. Clone Repo
2. Call `./install.sh --prompt --cdk-cmd create`
3. Bootstrap succeeds, but slurm deployment fails with the following error:
```
slurmminimal: creating CloudFormation changeset...

 ❌  slurmminimal failed: Error [ValidationError]: Unable to fetch parameters [/slurm/munge_key] from parameter store for this account.
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-05-12T16:48:12.685Z,
  requestId: 'xxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 542.6911270021684
```

**Expected behavior**
Expect the slurm app to be deployed

**Screenshots**

**Repository Version):**
14fe152bbc2cbe599486a1d050e40f3b6c3959a2

**Additional context**

**Comment by cartalla** [comment]
Confirmed. The ssm parameter name has a default name and it needs to be created and set if it doesn't already exist.
Otherwise, cannot give IAM permissions to the parameter so the slurm controller can read/write it.

**Comment by cartalla** [comment]
I was able to deploy a cluster using the bug's branch:

21-bug-deployment-fails-if-we-do-not-set-the-mungekeyssmparameter
