### ISSUE TITLE
[BUG] SlurmPlugin.py using wrong version of scontrol

### ISSUE THREAD

**Issue by cartalla** [aws-samples/aws-eda-slurm-cluster#53]
**Describe the bug**

The following exception occurred in power_save.log:

```
INFO:2022-08-22 13:54:37,696: Setting use1-az4-c7-x86-c6a-2xl-sp-0 to drain so new jobs do not run on it.
ERROR:2022-08-22 13:54:37,702: Unhandled exception while marking use1-az4-c7-x86-c6a-2xl-sp-0 down with reason=InsufficientInstanceCapacity
Traceback (most recent call last):
  File "/opt/slurm/slurmeda/bin/SlurmPlugin.py", line 1431, in mark_node_down
    self.drain(hostname, reason)
  File "/opt/slurm/slurmeda/bin/SlurmPlugin.py", line 1390, in drain
    subprocess.run([f"{self.config['SLURM_ROOT']}/bin/scontrol", 'update', f"nodename={hostname}", 'state=DRAIN', f"reason='{reason}'"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding='UTF-8') # nosec
  File "/usr/lib64/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/opt/slurm/slurmeda/slurm-22.05.2/AlmaLinux/8/x86_64/bin/scontrol'
```

Note that the slurmctl instance is running AmazonLinux2, not AlmaLinux8.
I'd seen this before where the AMI instance was updating the config file on the shared file system and thought I'd fixed it.
Need to do further debug.

**To Reproduce**

This occurred after an insufficient capacity exception.

**Expected behavior**

scontrol should successfully mark the node down.

**Repository Version**

8e2d864

**Comment by cartalla** [comment]
Didn't notice the date. This was an old error that has been resolved.
