### ISSUE TITLE
[BUG] Unable to recognise subnet || IndexError: list index out of range

### ISSUE THREAD

**Issue by vikram5889** [aws-samples/aws-eda-slurm-cluster#63]
Bootstrapping issue
***********************************
Traceback (most recent call last):
  File "/opt/aws-eda-slurm-cluster/source/app.py", line 31, in <module>
    CdkSlurmStack(app, app.node.try_get_context('stack_name'), env=cdk_env,
  File "/opt/aws-eda-slurm-cluster/source/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 100, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/opt/aws-eda-slurm-cluster/source/cdk/cdk_slurm_stack.py", line 114, in __init__
    self.create_vpc()
  File "/opt/aws-eda-slurm-cluster/source/cdk/cdk_slurm_stack.py", line 442, in create_vpc
    if valid_subnet_ids[0] == 'p-12345':
IndexError: list index out of range
***********************************
jsii.errors.JSIIError: There are no 'Private' subnet groups in this VPC. Available types: Isolated

**Comment by cartalla** [comment]
The root cause of the failure is because the VPC has only isolated subnets and no private subnets. This causes a variety of errors because the code assumes that there are private subnets.

**Comment by cartalla** [comment]
This bug has been fixed on the main branch. Please retry deployment.
